"""
JARVIS Tool Subsystem and Registry.
"""

from jarvis.tools.base import BaseTool, ToolMetadata, ToolResult
from jarvis.tools.computer_tools import (
    MoveMouseTool,
    ClickTool,
    DoubleClickTool,
    RightClickTool,
    ScrollTool,
    TypeTool,
    PressKeyTool,
    HotkeyTool,
    ScreenshotTool,
    ActiveWindowTool,
    ListWindowsTool,
    FocusWindowTool,
    CloseWindowTool,
)
from jarvis.tools.application_tools import (
    APPLICATION_TOOLS,
    ListApplicationsTool,
    FindApplicationTool,
    OpenApplicationTool,
    CloseApplicationTool,
    RestartApplicationTool,
    IsApplicationRunningTool,
    ListRunningApplicationsTool,
    FocusApplicationTool,
    CheckApplicationHealthTool,
    OpenApplicationFileTool,
    OpenApplicationUrlTool,
    ListStartupApplicationsTool,
)
from jarvis.tools.browser_tools import BROWSER_TOOLS
from jarvis.tools.filesystem_tools import FILESYSTEM_TOOLS, ListDirectoryTool, ReadFileTool, CreateFileTool, WriteFileTool, EditFileTool, CopyFileTool, MoveFileTool, RenameFileTool, CreateDirectoryTool, DeleteFileTool, DeleteDirectoryTool, SearchFilesTool, GetMetadataTool, FindDuplicatesTool, GetStorageInfoTool, OrganizeDirectoryTool
from jarvis.tools.shell_tools import SHELL_TOOLS, ExecuteShellCommandTool, GetShellEnvironmentTool, GetShellInfoTool, ListProcessesTool, GetProcessTool, TerminateProcessTool, JobStatusTool, JobOutputTool, CancelJobTool
from jarvis.tools.skill_tools import SKILL_TOOLS
from jarvis.tools.document_tools import (
    DOCUMENT_TOOLS,
    DocumentInspectTool,
    DocumentReadTool,
    DocumentExtractTextTool,
    DocumentSearchTool,
    DocumentSummarizeTool,
    DocumentAskTool,
    DocumentCompareTool,
    DocumentExtractTableTool,
    DocumentCreateTool,
    DocumentConvertTool,
)

ALL_TOOLS = [
    MoveMouseTool(),
    ClickTool(),
    DoubleClickTool(),
    RightClickTool(),
    ScrollTool(),
    TypeTool(),
    PressKeyTool(),
    HotkeyTool(),
    ScreenshotTool(),
    ActiveWindowTool(),
    ListWindowsTool(),
    FocusWindowTool(),
    CloseWindowTool(),
    *APPLICATION_TOOLS,
    *BROWSER_TOOLS,
    *FILESYSTEM_TOOLS,
    *SHELL_TOOLS,
    *SKILL_TOOLS,
    *DOCUMENT_TOOLS,
]

__all__ = [
    "BaseTool",
    "ToolMetadata",
    "ToolResult",
    "ALL_TOOLS",
    "APPLICATION_TOOLS",
    "BROWSER_TOOLS",
    "FILESYSTEM_TOOLS",
    "SHELL_TOOLS",
    "SKILL_TOOLS",
    "DOCUMENT_TOOLS",
    "MoveMouseTool",
    "ClickTool",
    "DoubleClickTool",
    "RightClickTool",
    "ScrollTool",
    "TypeTool",
    "PressKeyTool",
    "HotkeyTool",
    "ScreenshotTool",
    "ActiveWindowTool",
    "ListWindowsTool",
    "FocusWindowTool",
    "CloseWindowTool",
    "ListApplicationsTool",
    "FindApplicationTool",
    "OpenApplicationTool",
    "CloseApplicationTool",
    "RestartApplicationTool",
    "IsApplicationRunningTool",
    "ListRunningApplicationsTool",
    "FocusApplicationTool",
    "CheckApplicationHealthTool",
    "OpenApplicationFileTool",
    "OpenApplicationUrlTool",
    "ListStartupApplicationsTool",
    "ListDirectoryTool",
    "ReadFileTool",
    "CreateFileTool",
    "WriteFileTool",
    "EditFileTool",
    "CopyFileTool",
    "MoveFileTool",
    "RenameFileTool",
    "CreateDirectoryTool",
    "DeleteFileTool",
    "DeleteDirectoryTool",
    "SearchFilesTool",
    "GetMetadataTool",
    "FindDuplicatesTool",
    "GetStorageInfoTool",
    "OrganizeDirectoryTool",
    "ExecuteShellCommandTool",
    "GetShellEnvironmentTool",
    "GetShellInfoTool",
    "ListProcessesTool",
    "GetProcessTool",
    "TerminateProcessTool",
    "JobStatusTool",
    "JobOutputTool",
    "CancelJobTool",
    "DocumentInspectTool",
    "DocumentReadTool",
    "DocumentExtractTextTool",
    "DocumentSearchTool",
    "DocumentSummarizeTool",
    "DocumentAskTool",
    "DocumentCompareTool",
    "DocumentExtractTableTool",
    "DocumentCreateTool",
    "DocumentConvertTool",
]
