"""
Structured Tool Call Parser for Local LLM Output.
"""

import json
import re
from typing import Dict, Any, Optional, Tuple
from jarvis.brain.errors import ToolCallParseError


class StructuredToolParser:
    """
    Parses and validates structured JSON tool calls generated by the local language model.
    Format expected:
    {
      "tool": "filesystem.search",
      "arguments": {
        "query": "report.pdf"
      }
    }
    """

    @classmethod
    def parse_tool_call(cls, text: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
        """
        Parses text for a structured tool call.
        Returns (tool_name, arguments_dict, parse_error_message).
        """
        if not text or not text.strip():
            return None, None, "Empty model output."

        clean_text = text.strip()

        # Extract markdown code block json if present
        json_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", clean_text, re.DOTALL)
        if json_match:
            clean_text = json_match.group(1).strip()
        elif "{" in clean_text and "}" in clean_text:
            first_brace = clean_text.find("{")
            last_brace = clean_text.rfind("}")
            clean_text = clean_text[first_brace : last_brace + 1]

        try:
            data = json.loads(clean_text)
            if not isinstance(data, dict):
                return None, None, "Parsed JSON is not an object/dictionary."

            if "tool" not in data:
                return None, None, "Missing 'tool' key in JSON object."

            tool_name = data["tool"]
            args = data.get("arguments", data.get("args", {}))

            if not isinstance(tool_name, str):
                return None, None, "Tool name must be a string."

            if not isinstance(args, dict):
                return None, None, "Tool arguments must be a dictionary."

            return tool_name, args, None

        except json.JSONDecodeError as e:
            return None, None, f"JSON syntax error in tool call: {str(e)}"
